# Generated by Django 4.2.5 on 2023-09-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_price_product_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
    ]
