# Generated by Django 4.2.5 on 2023-09-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='amount',
        ),
    ]
